---
applications:
  root: ../../java-test-applications
  distZip:
    location: ${applications.root}/dist-zip-application
    prefix:   dist-zip-application-
  ejb:
    enabled:  false
    location: ${applications.root}/ejb-application
    prefix:   ejb-application-
  groovy:
    location: ${applications.root}/groovy-application
    prefix:   groovy-application-
  javaMain:
    location: ${applications.root}/java-main-application
    prefix:   java-main-application-
  ratpack:
    location: ${applications.root}/ratpack-application
    prefix:   ratpack-application-
  springBootCli:
    location: ${applications.root}/spring-boot-cli-application
    prefix:   spring-boot-cli-application-
  springBootCliJar:
    location: ${applications.root}/spring-boot-cli-jar-application
    prefix:   spring-boot-cli-jar-application-
  web:
    location: ${applications.root}/web-application
    prefix:   web-application-
  webServlet2:
    location: ${applications.root}/web-servlet-2-application
    prefix:   web-servlet-2-application-

services:
  mongodb:
    name:    test-mongodb
    service: mlab
    plan:    sandbox
  mysql:
    name:    test-mysql
    service: cleardb
    plan:    amp
  postgresql:
    name:    test-postgresql
    service: elephantsql
    plan:    hippo
  rabbitmq:
    name:    test-rabbitmq
    service: cloudamqp
    plan:    lemur
  redis:
    name:    test-redis
    service: rediscloud
    plan:    30mb
