---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfje/java-buildpack-system-test
    username: ((docker-username))
    password: ((docker-password))

inputs:
- name: java-buildpack-system-test
- name: om

outputs:
- name: environment

run:
  path: java-buildpack-system-test/ci/claim-environment.sh

params:
  API_TOKEN:
